import React, { useState, useEffect } from 'react';
import { FileText, Download, Copy, Loader, Share2 } from 'lucide-react';
import { useParams } from 'react-router-dom'; // Added useParams hook
import apiClient from '../../config/apiClient'; // Fixed import path to config folder

const AISessionSummary = () => {
  // Extract the 'id' parameter from the URL matching the route "/sessions/:id/summary"
  const { id } = useParams(); 

  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    // Moved fetch function inside useEffect to follow React best practices 
    // and prevent dependency array warnings
    const fetchSessionSummary = async () => {
      setLoading(true);
      setError(null);
      try {
        const response = await apiClient.get(`/ai/sessions/${id}/summary`);
        setSummary(response.data || response);
      } catch (err) {
        console.error('Failed to fetch summary:', err);
        setError('Failed to generate session summary');
      } finally {
        setLoading(false);
      }
    };

    if (id) {
      fetchSessionSummary();
    }
  }, [id]);
  
  const handleCopy = () => {
    const text = `${summary.title}\n\n${summary.key_points.join('\n')}\n\n${summary.main_takeaways}`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const content = `
${summary.title}
${'='.repeat(50)}

KEY POINTS:
${summary.key_points.map((point, i) => `${i + 1}. ${point}`).join('\n')}

MAIN TAKEAWAYS:
${summary.main_takeaways}

SKILLS LEARNED:
${summary.skills_learned?.join(', ') || 'N/A'}

ACTION ITEMS:
${summary.action_items?.join('\n') || 'N/A'}

Generated by EventAI Assistant
${new Date().toLocaleDateString()}
    `;

    const element = document.createElement('a');
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(content));
    element.setAttribute('download', `${summary.title.replace(/\s+/g, '_')}_summary.txt`);
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="min-h-screen bg-white dark:bg-slate-950">
      {/* Header */}
      <div className="bg-gradient-to-r from-blue-500 to-blue-600 text-white p-6 pt-8">
        <div className="flex items-center gap-3 mb-2">
          <FileText size={32} />
          <h1 className="text-3xl font-bold">Session Summary</h1>
        </div>
        <p className="text-blue-100">AI-generated recap of what you learned</p>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto p-6">
        {loading ? (
          <div className="text-center py-12">
            <Loader size={48} className="text-blue-500 mx-auto mb-4 animate-spin" />
            <p className="text-lg text-slate-600 dark:text-slate-400">
              Generating your summary...
            </p>
          </div>
        ) : error ? (
          <div className="p-6 bg-red-100 dark:bg-red-900/30 border border-red-300 dark:border-red-700 text-red-700 dark:text-red-300 rounded-lg text-center">
            <p className="mb-4">{error}</p>
            <button
              onClick={fetchSessionSummary}
              className="px-4 py-2 bg-red-600 hover:bg-red-700 text-white rounded-lg font-medium transition-colors"
            >
              Try Again
            </button>
          </div>
        ) : summary ? (
          <div className="space-y-6">
            {/* Action Buttons */}
            <div className="flex flex-wrap gap-3">
              <button
                onClick={handleCopy}
                className={`flex items-center gap-2 px-4 py-2 rounded-lg font-medium text-sm transition-all duration-200 ${
                  copied
                    ? 'bg-green-500 text-white'
                    : 'bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 hover:bg-blue-200 dark:hover:bg-blue-900/50'
                }`}
              >
                <Copy size={16} />
                {copied ? 'Copied!' : 'Copy'}
              </button>
              <button
                onClick={handleDownload}
                className="flex items-center gap-2 px-4 py-2 rounded-lg font-medium text-sm bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 hover:bg-blue-200 dark:hover:bg-blue-900/50 transition-all duration-200"
              >
                <Download size={16} />
                Download
              </button>
              <button className="flex items-center gap-2 px-4 py-2 rounded-lg font-medium text-sm bg-slate-200 dark:bg-slate-700 text-slate-700 dark:text-slate-300 hover:bg-slate-300 dark:hover:bg-slate-600 transition-all duration-200">
                <Share2 size={16} />
                Share
              </button>
            </div>

            {/* Title */}
            <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-700 rounded-lg p-6">
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-2">
                {summary.title}
              </h2>
              <p className="text-sm text-slate-600 dark:text-slate-400">
                2-minute read • AI-generated summary
              </p>
            </div>

            {/* Key Points */}
            <div>
              <h3 className="text-xl font-semibold text-slate-900 dark:text-white mb-4">
                📌 Key Points
              </h3>
              <div className="space-y-3">
                {summary.key_points?.map((point, idx) => (
                  <div
                    key={idx}
                    className="flex gap-4 p-4 bg-slate-50 dark:bg-slate-800 rounded-lg border border-slate-200 dark:border-slate-700 hover:shadow-md transition-shadow"
                  >
                    <div className="flex-shrink-0 w-8 h-8 bg-blue-500 text-white rounded-full flex items-center justify-center font-semibold">
                      {idx + 1}
                    </div>
                    <p className="text-slate-700 dark:text-slate-300 text-sm leading-relaxed">
                      {point}
                    </p>
                  </div>
                ))}
              </div>
            </div>

            {/* Main Takeaways */}
            <div className="bg-gradient-to-r from-purple-50 to-pink-50 dark:from-purple-900/20 dark:to-pink-900/20 border border-purple-200 dark:border-purple-700 rounded-lg p-6">
              <h3 className="text-xl font-semibold text-slate-900 dark:text-white mb-3">
                💡 Main Takeaways
              </h3>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
                {summary.main_takeaways}
              </p>
            </div>

            {/* Skills Learned */}
            {summary.skills_learned && summary.skills_learned.length > 0 && (
              <div>
                <h3 className="text-xl font-semibold text-slate-900 dark:text-white mb-4">
                  🎓 Skills You Learned
                </h3>
                <div className="flex flex-wrap gap-2">
                  {summary.skills_learned.map((skill, idx) => (
                    <div
                      key={idx}
                      className="px-4 py-2 bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 rounded-full text-sm font-medium"
                    >
                      {skill}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Action Items */}
            {summary.action_items && summary.action_items.length > 0 && (
              <div>
                <h3 className="text-xl font-semibold text-slate-900 dark:text-white mb-4">
                  ✅ Action Items
                </h3>
                <div className="space-y-2">
                  {summary.action_items.map((item, idx) => (
                    <div
                      key={idx}
                      className="flex items-center gap-3 p-3 bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-700 rounded-lg"
                    >
                      <input
                        type="checkbox"
                        className="w-5 h-5 text-green-600 dark:text-green-400 rounded focus:ring-2 focus:ring-green-500"
                      />
                      <label className="text-slate-700 dark:text-slate-300 text-sm cursor-pointer">
                        {item}
                      </label>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Next Steps */}
            <div className="bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg p-6">
              <h3 className="text-lg font-semibold text-slate-900 dark:text-white mb-3">
                📚 What's Next?
              </h3>
              <ul className="space-y-2 text-slate-700 dark:text-slate-300 text-sm">
                <li>• Take the quiz to test your knowledge</li>
                <li>• Connect with other attendees</li>
                <li>• Save related sessions for later</li>
                <li>• Download resources shared in the session</li>
              </ul>
            </div>

            {/* Footer */}
            <div className="text-center pt-6 border-t border-slate-200 dark:border-slate-700">
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Summary generated by EventAI • {new Date().toLocaleDateString()}
              </p>
            </div>
          </div>
        ) : null}
      </div>
    </div>
  );
};

export default AISessionSummary;